"""empty message

Revision ID: c36874cc1884
Revises: 
Create Date: 2018-03-20 23:34:18.894981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36874cc1884'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=80), nullable=True),
    sa.Column('LastName', sa.String(length=80), nullable=True),
    sa.Column('Gender', sa.String(length=80), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('Location', sa.String(length=80), nullable=True),
    sa.Column('Biography', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.String(length=80), nullable=True),
    sa.Column('picture', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
